apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jvm-monitor 
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: jvm-metrics
  endpoints:
  - port: metrics
    interval: 30s
    relabelings:
      - action: replace
        regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
        replacement: '[$2]:$1'
        sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port","__meta_kubernetes_pod_ip"]
        targetLabel: "__address__"
      - action: replace
        regex: (\d+);((([0-9]+?)(\.|$)){4})
        replacement: '$2:$1'
        sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port","__meta_kubernetes_pod_ip"]
        targetLabel: "__address__"
