apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jvm-monitor 
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      app: jvm-metrics
  endpoints:
  - port: metrics
    interval: 5s
    path: /metrics