apiVersion: v1
kind: Secret
metadata:
  name: db-cert
type: Opaque
data:
  server.crt: |
    # Base64 encode your certificate file
    # Example: base64 -w 0 path/to/your/certificate.crt
    # valueFrom: { secretKeyRef: { name: pgo-root-cacert, key: root.crt } }

