apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-postgres-app
  template:
    metadata:
      labels:
        app: java-postgres-app
    spec:
      containers:
      - name: java-postgres-app
        image: docker.io/ashafqat/javapostgresapp:v0.8
        # v0.9 version of image doesn't uses tls: docker.io/ashafqat/javapostgresapp:v0.9-non-tls
        volumeMounts:
        - name: ssl-cert
          mountPath: /tmp
        env:
        - name: SSL_CERT
          value: /tmp/server.crt
        - name: DB_USER
          #valueFrom: { secretKeyRef: { name: ort1-str-region-1-rw-pguser-ort1-str-region-1-rw, key: user } }
          value: java-user
        - name: DB_PASSWORD
          #valueFrom: { secretKeyRef: { name: ort1-str-region-1-rw-pguser-ort1-str-region-1-rw, key: password } }
          value: ""
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "bookstore"
        - name: TABLE_NAME
          value: "books"
        - name: DB_HOST
          value: "ort1-str-region-1-rw-primary.pgd-group.svc.cluster.local"
      volumes:
      - name: ssl-cert
        secret:
          secretName: db-cert
